// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY-YqOX0wVfc9f3JqIborbPQhT5pOZf9c',
    appId: '1:668777250322:web:4457017b6828403d11e2cb',
    messagingSenderId: '668777250322',
    projectId: 'mes-pro-796e2',
    authDomain: 'mes-pro-796e2.firebaseapp.com',
    databaseURL: 'https://mes-pro-796e2-default-rtdb.firebaseio.com',
    storageBucket: 'mes-pro-796e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDT0zR2TYERqKVhvB20lpCvgtLOjzJgY8',
    appId: '1:668777250322:android:723aaed7c234505e11e2cb',
    messagingSenderId: '668777250322',
    projectId: 'mes-pro-796e2',
    databaseURL: 'https://mes-pro-796e2-default-rtdb.firebaseio.com',
    storageBucket: 'mes-pro-796e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUe3bSTVnS2CJGmL9yLqv8z9dvbit7ws',
    appId: '1:668777250322:ios:83722a1730cdb58b11e2cb',
    messagingSenderId: '668777250322',
    projectId: 'mes-pro-796e2',
    databaseURL: 'https://mes-pro-796e2-default-rtdb.firebaseio.com',
    storageBucket: 'mes-pro-796e2.appspot.com',
    iosClientId: '668777250322-32d94ch5qn1cv5atv776bpratktcfgn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mesPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoUe3bSTVnS2CJGmL9yLqv8z9dvbit7ws',
    appId: '1:668777250322:ios:83722a1730cdb58b11e2cb',
    messagingSenderId: '668777250322',
    projectId: 'mes-pro-796e2',
    databaseURL: 'https://mes-pro-796e2-default-rtdb.firebaseio.com',
    storageBucket: 'mes-pro-796e2.appspot.com',
    iosClientId: '668777250322-32d94ch5qn1cv5atv776bpratktcfgn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mesPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY-YqOX0wVfc9f3JqIborbPQhT5pOZf9c',
    appId: '1:668777250322:web:85fd3a755d3ca28911e2cb',
    messagingSenderId: '668777250322',
    projectId: 'mes-pro-796e2',
    authDomain: 'mes-pro-796e2.firebaseapp.com',
    databaseURL: 'https://mes-pro-796e2-default-rtdb.firebaseio.com',
    storageBucket: 'mes-pro-796e2.appspot.com',
  );
}
